Added usage, query string and updated args

diff --git a/random/dmgLoopDSCore/dmgLoopDSCore b/random/dmgLoopDSCore/dmgLoopDSCore
--- a/random/dmgLoopDSCore/dmgLoopDSCore
+++ b/random/dmgLoopDSCore/dmgLoopDSCore
@@ -22,7 +22,8 @@
 # Usage: ./dmgLoopDSCore [options] <argv>...
 #
 # Options:
-#  -p       (Optional) Path to directory to search for .dmg files
+#  -i       (Optional) Input directory to search for .dmg files
+#  -q                  Query string
 
 #//////////////////////////////////////////////////////////////////////////////////////////////////
 ###
@@ -53,6 +54,14 @@ remove_temporary_directories() {
     done
 }
 
+usage() {
+    printf "%s\n" "Usage: ./${0##*/} [options] <argv>..."
+    printf "%s\n" "Options:"
+    printf "  %s\t%s\n" "-i" "(Optional) Input directory"
+    printf "  %s\t%s\n" "-q" "Query string"
+    printf "\n"
+}
+
 error() {
     printf "%s\n" "${1}, exiting script..." >&2; exit 1
 }
@@ -60,14 +69,19 @@ error() {
 parse_opts() {
     while getopts "p:" opt; do
         case ${opt} in
-            p) path="${OPTARG}" ;;
-            \?) printf "%s\n" "Invalid option: -${OPTARG}" ;;
-            :) printf "%s\n" "Option -${OPTARG} requires an argument." ;;
+            i) input_directory="${OPTARG}" ;;
+            q) query_string="${OPTARG}" ;;
+            \?) usage; exit 1 ;;
+            :) usage; exit 1 ;;
         esac
     done
     
-    if [[ -n ${path} ]] && ! [[ -d ${path} ]]; then
-        error "${path} is not a directory"
+    if [[ -n ${input_directory} ]] && ! [[ -d ${input_directory} ]]; then
+        error "${input_directory} is not a directory"
+    fi
+    
+    if [[ -z ${query_string} ]]; then
+        usage; exit 1 ;;
     fi
 }
 
@@ -86,7 +100,7 @@ parse_image() {
     
     # Extract DSCore.framework binary to extraction_dir.
     if (cd ${extraction_dir} && gunzip -c "${mountpoint}"/DeployStudio*.mpkg/Contents/Packages/deploystudioAdmin.pkg/Contents/Archive.pax.gz | pax -r -s ":./DeployStudio Admin.app/Contents/Frameworks/DSCore.framework/Versions/A:${extraction_dir}:" "./DeployStudio Admin.app/Contents/Frameworks/DSCore.framework/Versions/A/DSCore"); then
-        if grep -q '1YL601802TQ' "${extraction_dir}/DSCore"; then
+        if grep -q "${query_string}" "${extraction_dir}/DSCore"; then
             printf "%s\n" "DeployStudio version: ${ds_version} - FOUND"
         else
             printf "%s\n" "DeployStudio version: ${ds_version} - NOT FOUND"
@@ -95,7 +109,7 @@ parse_image() {
         error "Extracting DSCore failed"
     fi
     
-    # Remove the extracted DSCore binary to clean up for next iteration.
+    # Remove the extracted DSCore binary to clean up before next iteration.
     if ! rm "${extraction_dir}/DSCore"; then
         error "Removing DSCore failed"
     fi
@@ -124,7 +138,7 @@ trap remove_temporary_directories INT EXIT
 shopt -s nullglob
 
 # Loop through all .dmg-files found in passed directory (or current working directory if no directory was passed).
-for dmg in "${path:-${PWD}}"/*\.dmg; do
+for dmg in "${input_directory:-${PWD}}"/*\.dmg; do
         
     # If anything is attached to the mountpoint, try to detach it first.
     if diskutil info "${mountpoint}" >/dev/null 2>&1; then
